server.port=8080

spring.data.mongodb.uri=mongodb+srv://prayasambawade:Prayas123@cluster0.t1ktek3.mongodb.net/cloud_analyzer_db

logging.level.org.springframework.data.mongodb=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prayasambawade@gmail.com
spring.mail.password=pktegmyqhahtihby
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

openai.api-key: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
