# Update the database name at the end of the URI string
spring.data.mongodb.uri=mongodb+srv://cloud_analyzer_db:Prayas1110@cluster0.mongodb.net/cloud_analyzer_db?retryWrites=true&w=majority
spring.data.mongodb.database=cloud_analyzer_db